version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: black
    versions:
    - 21.4b0
    - 21.4b1
  - dependency-name: faker
    versions:
    - 8.1.0
  - dependency-name: pre-commit
    versions:
    - 2.11.0
    - 2.11.1
    - 2.12.0
  - dependency-name: pytest
    versions:
    - 6.2.3
  - dependency-name: google-cloud-pubsub
    versions:
    - 2.4.0
    - 2.4.1
  - dependency-name: numpy
    versions:
    - 1.20.2
  - dependency-name: google-cloud-bigquery
    versions:
    - 2.10.0
    - 2.11.0
    - 2.12.0
    - 2.13.0
    - 2.13.1
  - dependency-name: isort
    versions:
    - 5.8.0
  - dependency-name: flake8
    versions:
    - 3.9.0
  - dependency-name: pydantic
    versions:
    - 1.8.1
